name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t professor7xh/area51
    - name: login
      run: docker login -u professor7xh -p Harsh@#1234 && docker push professor7xh/area51
